### ISSUE TITLE
Link to repositories

### ISSUE THREAD

**Issue by ghost** [dt/ghlink#6]
It'd be really cool if you could also use this to link to a repository by using `@username/repository`.
/CC @dt

**Comment by deltaidea** [comment]
Hey! Sounds great, I'm gonna implement it.
Hope it doesn't conflict with any similar notation `@foo/bar` in some language. That's the only concern.

**Comment by ghost** [comment]
Awesome, thank you so much for addressing this 😄 Let's continue the conversation about the implementation of it over in #7.
